name: Daily Dog Scrape

on:
  schedule:
    # Runs every 24 hours at midnight UTC
    - cron: '0 0 * * *'

  workflow_dispatch: # Allows you to manually trigger the workflow
    inputs: {}

jobs:
  run-dog-scrape:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install supabase
          pip install python-dotenv

      # Run the scraping script
      - name: Run Dog Scrape
        run: |
          python beautiful-together-next/scraping/dog_scrape.py
